# Use the official MySQL 5.7 image from Docker Hub
FROM mysql:5.7

# Set environment variables to configure MySQL
ENV MYSQL_ROOT_PASSWORD=example
ENV MYSQL_DATABASE=test_db

# Expose the default MySQL port
EXPOSE 3306
