FROM almalinux:9
ENV MY_NAME="T Krishna" \
   MY_DOG="Rex" \
    MY_CAT="fluffy" 
LABEL ENV="DEV" \
      Project="Docker LABEL" \
      AWS="ec2 instance"
EXPOSE 80
# CMD [ "ping", "google.com" ]
 ENTRYPOINT [ "ping", "google.com" ]
# CMD [ "google.com"]
# ENTRYPOINT [ "ping" ]