CREATE DATABASE IF NOT EXISTS Tech_Base_Hub_DB;
USE Tech_Base_Hub_DB;

CREATE TABLE IF NOT EXISTS submissions (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100),
    email VARCHAR(100)
);
