FROM almalinux:9
ENV MY_NAME="John Doe" \
    MY_DOG="Rex" \
    MY_CAT="fluffy" 
RUN dnf install nginx -y
LABEL ENV="DEV" \
      Project="Docker LABEL" \
      AWS="ec2 instance"
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]