FROM almalinux:9
ENV MY_NAME="John Doe" \
    MY_DOG="Rex" \
    MY_CAT="fluffy" 
    LABEL ENV="DEV" \
    Project="Docker LABEL" \
    AWS="ec2 instance"
EXPOSE 80
RUN useradd krishnatummeti
USER krishnatummeti
RUN dnf install nginx -y
CMD ["nginx", "-g", "daemon off;"]