FROM almalinux:9
ENV MY_NAME="John Doe" \
    MY_DOG="Rex" \
    MY_CAT="fluffy" 

LABEL ENV="DEV" \
    Project="Docker LABEL" \
    AWS="ec2 instance"

EXPOSE 8080

RUN dnf install nginx -y && dnf clean all

RUN useradd krishnatummeti

USER krishnatummeti

CMD ["nginx", "-g", "daemon off;"]